<? $a = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>
<li><a href="<?=$this->baseUrl('/admin')?>" class="<?=$a == 'index' ? 'current' : ''?>">Pagina Inicial</a></li>
<!--<li><a href="<?//=$this->baseUrl('/admin/usuarios')?>" class="<?//=$a == 'usuarios' ? 'current' : ''?>">Usuarios</a></li>-->
<li><a href="<?=$this->baseUrl('/admin/palestras')?>" class="<?=$a == 'palestras' ? 'current' : ''?>">Palestras</a></li>
<li><a href="<?=$this->baseUrl('/admin/relatorios')?>" class="<?=$a == 'relatorios' ? 'current' : ''?>">Relatórios</a></li>
<li><a href="<?=$this->baseUrl('/admin/usuarios')?>" class="<?=$a == 'usuarios' ? 'current' : ''?>">Usuários</a></li>
<li><a href="<?=$this->baseUrl('/admin/sair')?>" class="<?=$a == 'sair' ? 'current' : ''?>">Sair</a></li> 