<? $c = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<li><a href="<?=$this->baseUrl('/index')?>" class="<?=$c == 'index' ? 'current' : ''?>">Pagina Inicial</a></li>
<li><a href="<?=$this->baseUrl('/objetivo')?>" class="<?=$c == 'objetivo' ? 'current' : ''?>">Objetivo</a></li>
<li><a href="<?=$this->baseUrl('/inscricao')?>" class="<?=$c == 'inscricao' ? 'current' : ''?>">Inscrições</a></li>
<li><a href="<?=$this->baseUrl('/programacao')?>" class="<?=$c == 'programacao' ? 'current' : ''?>">Programação</a></li>
<li><a href="<?=$this->baseUrl('/contato')?>" class="<?=$c == 'contato' ? 'current' : ''?>">Contato</a></li>
<div id="btFacebook" class="fb-like" data-href="https://www.facebook.com/sactaunipampa?fref=ts" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>