<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div>
            <p>Olá, <?=$this->nome;?></p>
            <p>Para confirmação da sua inscrição, clique no link abaixo:</p>
            <p><a href="<?=$this->link?>"><?=$this->link?></a></p>
            <footer>
                <p><small><?=$this->title?></small></p>
            </footer>
    </body>
</html>
