<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div>
            <p>Bom dia / Boa tarde / Boa noite, <?=$this->nome;?></p>
            <p>Esta é confirmação da pré-inscrição na Semana Acadêmica 2013!<br>
                A pré-inscrição não garante participação no evento.<br>
                A inscrição será realizada após o credenciamento.</p>
            <p>Orientações:</p>
            <ul>
                <li>Para o CREDENCIAMENTO levar documento de identidade com foto (CNH, RG, passaporte, CT), e pagar uma taxa de R$ 10,00 que dará acesso às palestras, mini-cursos e visitas técnicas.</li>
                <li>O participante receberá um crachá que deve ser utilizado durante todo o evento.</li>
                <li>Em cada sala terá controle de entrada/saída feito por meio do código de barras que estará no próprio crachá. Toda a entrada e toda a saída de cada participante deverá ser registrada.</li>
                <li>A inscrição de um participante em duas palestras simultâneas resultará em anulação da participação em ambas.</li>
                <li>A participação para VISITAS TÉCNICAS e MINI-CURSOS se darão por meio de inscrição no ato do credenciamento, ou seja, o usuario interessado deve colocar nome na lista que estará disponível no dia do credenciamento.</li>
                <li>O número de vagas para essas visitas técnicas e mini-cursos dependem do espaço fisico do local. A prioridade é pela ordem de inscrição.</li>
                <li>As listas de presença das palestras serão entregue aos professores para que cada um decida se vai dar falta para quem não for na semana acadêmica</li>
            </ul>
            <p>Quanto a certificação:</p>
            <ul>
                <li>O participante terá direito ao certificado caso comparecer em uma ou mais palestras válidas. Cada palestra será considerada válida, ou seja, entrará na contagem de horas válidas para a certificação, caso o participante estiver presente em mais de 70% da palestra.</li>
                <li>As palestras podem ter uma duração variada, então a contagem de tempo de cada palestra será feita individualmente. Se uma palestra de duas horas apenas dure uma hora e meia, o participante deverá estar presente em 70% de uma hora e meia. Porém essas duas horas que foram registradas para a palestra que irão aparecer no certificado.</li>
                <li>No momento que é feita a inscrição, o participante ganha automaticamente quatro horas, que equivale ao tempo do credenciamento.</li>
            </ul>
            <p>Atividades fora da programação serão notificadas nos telões da programação.</p>
        </div>
    </body>
</html>
