<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div>
            Nome: <?= $this->nome ?> <br/>
            Email: <?= $this->email ?> <br/>
            Telefone: <?= $this->telefone ?> <br/>
            Mensagem: <?= $this->mensagem ?>
        </div>
    </body>
</html>