language: php
php:
  - "5.4"
  
branches:
  only:
    - v1.0

script: phpunit --configuration tests/phpunit.xml 

before_install:
  - svn checkout --quiet http://framework.zend.com/svn/framework/standard/trunk/library/Zend/ library/Zend/
  - cp application/configs/application.ini.dist application/configs/application.ini
