language: php
php:
  - "5.4"
  
branches:
  only:
    - v1.0

script:
  - phpunit --version
  - phpunit --configuration tests/phpunit_travis.xml --bootstrap tests/bootstrap.php

before_install:
  - svn checkout --quiet http://framework.zend.com/svn/framework/standard/trunk/library/Zend/ library/Zend/
  - svn checkout --quiet http://framework.zend.com/svn/framework/extras/trunk/library/ZendX/ library/ZendX/
  - cp application/configs/application.ini.dist application/configs/application.ini

  - sudo pear config-set auto_discover 1
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear uninstall pear.phpunit.de/PHPUnit
  - sudo pear install --alldeps pear.phpunit.de/PHPUnit-3.4.15
  
  - pecl install apc
  - echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`