language: php
php:
  - "5.4"
branches:
  only:
    - v1.0

script: phpunit --configuration tests/phpunit.xml

before_install:
  - svn checkout http://framework.zend.com/svn/framework/standard/trunk library/Zend/