<h2>Bem-vindo!</h2>
<hr />
<p>Chegamos a mais uma edição da Semana Acadêmica, e os preparativos para a edição de 2014 já iniciaram. Aqui você vai ficar sabendo do andamento da organização da Semana Acadêmica 2014 e também poderá contribuir com sugestões para as edições futuras do evento.</p>
<br><br>

<h4>Relação de pessoal inscrito para a "Visita Técnica á Usina Termoelétrica de Alegrete" em 25/07/2014:</h4>
<a href="https://docs.google.com/spreadsheets/d/1-l9k_RbJFALuPApTiYsQMMvHMiNeRdZI4YbCkNwiKrk/edit#gid=0" target="_blank"> Clique aqui!</a> 
