<h2>Inscrições</h2>
<hr />
<p>Efetue sua inscrição para a Semana Acadêmica 2014 no botão abaixo!</p>
<br />

<div class="botao">
    <a href="<?= $this->baseUrl('/inscricao/inscrever') ?>">Inscrever</a>
</div>
<br />
<p>Faça seu pré-cadastro neste link e no dia do evento efetue o pagamento para efetivar sua inscrição. Assim que efetuar a sua inscrição, você receberá no seu e-mail instruções de como proceder após efetuar esta operação.</p>
<p>O valor da inscrição é de R$ 20,00. Esse valor será pago no credenciamento, no qual lhe darão o crachá com o seu código de barras.</p>
<br />
<br />
<p>Caso não tenha recebido o e-mail de confirmação, clique no boão abaixo para reenviar a confirmação de e-mail.</p>
<br />
<div class="botao">
    <a href="<?= $this->baseUrl('/inscricao/reenviar') ?>">Reenviar e-mail de confirmação</a>
</div>