<h2>Inscrições</h2>
<p>As inscrições devem ser feitas clicando no botão abaixo</p>
<br />
<div class="botao">
    <a href="<?= $this->baseUrl('/inscricao/inscrever') ?>">Inscrever</a>
</div>
<br />
<p>Faça seu pré-cadastro neste link e no dia do evento efetue o pagamento para efetivar sua inscrição. Assim que efetuar a sua inscrição, você receberá no seu e-mail instruções de como proceder após efetuar esta operação.</p>
<p>O valor da inscrição é de R$ 10,00. Esse valor será pago no credenciamento, no qual lhe darão o crachá com o seu código de barras.</p>
<br />