<div id="view-content">
    <h1>Credenciar Ouvinte: <?= $this->usuario->getNome()?></h1> 
    <div id="pagar">
        <form method="POST" action>
            <p>Valor: <input name="valor" type="text" value=""></p>
            <p>Forma de pagamento: 
                <select name="formaPagamento">
                    <? foreach ($this->formasPagamento as $formaPagamento) : ?>
                        <option><?= $formaPagamento->getDescricao() ?></option>
                    <? endforeach; ?>
                </select>
            </p>
            <p><input type="submit" value="Pagar" class="button"/></p>
        </form>
    </div>
    <div id="isentar">
        <form method="POST" action>
            <p>Motivo: <textarea name="motivo" cols="60" rows="10"></textarea></p>
            <p><input type="submit" value="Isentar" class="button"/></p>
        </form>
    </div>
</div>