/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author PC
 */
public class ListaPalestras extends javax.swing.JFrame {

    public static Logger logger = Logger.getLogger(ListaPalestras.class);
    private ArrayList<Sessao> sessao = new ArrayList<>();

    /**
     * Creates new form ListaPalestras
     */
    public ListaPalestras() {
        initComponents();

    }

    /**
     * Metodo que centraliza a interface na tala.
     *
     * @param componente
     */
    protected static void centralizar(Component componente) {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Rectangle r = componente.getBounds();

        int widthSplash = r.width;
        int heightSplash = r.height;

        int posX = (screen.width / 2) - (widthSplash / 2);
        int posY = (screen.height / 2) - (heightSplash / 2);

        componente.setBounds(posX, posY, widthSplash, heightSplash);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scr_Pane1 = new javax.swing.JScrollPane();
        Tab_ListaPalestras = new javax.swing.JTable();
        Lab_ListaPalestras = new javax.swing.JLabel();
        But_GerenPalestra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab_ListaPalestras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tab_ListaPalestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Identificador", "Nome", "Palestrante", "Local"
            }
        ));
        Scr_Pane1.setViewportView(Tab_ListaPalestras);
        Tab_ListaPalestras.getColumnModel().getColumn(0).setMinWidth(90);
        Tab_ListaPalestras.getColumnModel().getColumn(0).setMaxWidth(90);

        Lab_ListaPalestras.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Lab_ListaPalestras.setText("Lista de Palestras");

        But_GerenPalestra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        But_GerenPalestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/demo.png"))); // NOI18N
        But_GerenPalestra.setText("Dados da Palestra");
        But_GerenPalestra.setToolTipText("<html>\n<body>\n<b>Botão para visualizar os dados da Palestra selecionada.</b>\n</bode>\n</html>");
        But_GerenPalestra.setName("Gerênciar Palestra"); // NOI18N
        But_GerenPalestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_GerenPalestraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Scr_Pane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lab_ListaPalestras)
                        .addGap(282, 282, 282))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(But_GerenPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lab_ListaPalestras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Scr_Pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(But_GerenPalestra)
                .addContainerGap())
        );

        But_GerenPalestra.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void But_GerenPalestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_GerenPalestraActionPerformed

        try {


            Sessao objSessao = new Sessao(null);

            this.dispose();
            objSessao.setVisible(true);
            centralizar(objSessao);

        } catch (Exception error) {

            java.util.logging.Logger.getLogger(ListaPalestras.class.getName()).log(Level.SEVERE, null, error);
        }
    }//GEN-LAST:event_But_GerenPalestraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPalestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPalestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPalestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPalestras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPalestras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_GerenPalestra;
    private javax.swing.JLabel Lab_ListaPalestras;
    private javax.swing.JScrollPane Scr_Pane1;
    private javax.swing.JTable Tab_ListaPalestras;
    // End of variables declaration//GEN-END:variables
}
