/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Palestra;

/**
 *
 * @author nasser
 */
public class ViewPalestra extends javax.swing.JFrame {
    Palestra p = new Palestra();
    /**
     * Creates new form ViewPalestra
     */
    public ViewPalestra() {
        initComponents();
    }
    
    public ViewPalestra(Palestra pa) {
        initComponents();
        this.p = pa;
        jlblNomePalestra.setText(p.getNomePalestra().toString());
        jlblNomePalestrante.setText(p.getNomePalestrante().toString());
        jlblInstituicao.setText(p.getInstituicao().toString());
        //jlblHoraInicioPrevista.setText(p.getHoraInicioPrevista().toString());
        //jlblHoraTerminoPrevista.setText(p.getHoraFimPrevista().toString());
        
        jlblHoraInicioPrevistaHora.setText(p.getHoraInicioPrevista().toString());
        jlblHoraTerminoPrevistoHora.setText(p.getHoraFimPrevista().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("client-offlinePU").createEntityManager();
        sessaoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Sessao s");
        sessaoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : sessaoQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jbtnIniciarPalestra = new javax.swing.JButton();
        jbtnFinalizarPalestra = new javax.swing.JButton();
        jlblNomePalestrante = new javax.swing.JLabel();
        jlblOuvintes = new javax.swing.JLabel();
        jlblInformeCodigoBarras = new javax.swing.JLabel();
        jftfCodigoBarras = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnAdd = new javax.swing.JButton();
        jlblHoraInicio = new javax.swing.JLabel();
        jlblHoraInicioHora = new javax.swing.JLabel();
        jlblHoraTermino = new javax.swing.JLabel();
        jlblHoraTerminoHora = new javax.swing.JLabel();
        jlblHoraInicioPrevista = new javax.swing.JLabel();
        jlblHoraInicioPrevistaHora = new javax.swing.JLabel();
        jlblHoraTerminoPrevista = new javax.swing.JLabel();
        jlblHoraTerminoPrevistoHora = new javax.swing.JLabel();
        jlblTempoDecorrido = new javax.swing.JLabel();
        jlblTempoDecorridoHora = new javax.swing.JLabel();
        jlblHoraAtual = new javax.swing.JLabel();
        jlblHoraAtualHora = new javax.swing.JLabel();
        jbtnAdd1 = new javax.swing.JButton();
        jlblNomePalestra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblInstituicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbtnIniciarPalestra.setText("Iniciar Palestra");
        jbtnIniciarPalestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarPalestraActionPerformed(evt);
            }
        });

        jbtnFinalizarPalestra.setText("Finalizar Palestra");

        jlblNomePalestrante.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblNomePalestrante.setText("Palestrante");

        jlblOuvintes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblOuvintes.setText("Ouvintes que estão ou estavam na palestra:");

        jlblInformeCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblInformeCodigoBarras.setText("Informe o código de barras:");

        jftfCodigoBarras.setText("12345");
        jftfCodigoBarras.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sessaoList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idOuvinte.nome}"));
        columnBinding.setColumnName("Ouvinte");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idOuvinte.codigoBarras}"));
        columnBinding.setColumnName("Código Barras");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaEntrada}"));
        columnBinding.setColumnName("Entrada");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaSaida}"));
        columnBinding.setColumnName("Saida");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jlblHoraInicio.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblHoraInicio.setText("Hora de início:");

        jlblHoraInicioHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblHoraInicioHora.setForeground(new java.awt.Color(0, 125, 0));
        jlblHoraInicioHora.setText("08:03:51");

        jlblHoraTermino.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblHoraTermino.setText("Hora de término:");

        jlblHoraTerminoHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblHoraTerminoHora.setForeground(new java.awt.Color(125, 0, 0));
        jlblHoraTerminoHora.setText("::");

        jlblHoraInicioPrevista.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblHoraInicioPrevista.setText("Início previsto:");

        jlblHoraInicioPrevistaHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblHoraInicioPrevistaHora.setText("08:00:00");

        jlblHoraTerminoPrevista.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblHoraTerminoPrevista.setText("Término previsto:");

        jlblHoraTerminoPrevistoHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblHoraTerminoPrevistoHora.setText("10:30:00");

        jlblTempoDecorrido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblTempoDecorrido.setText("Tempo decorrido:");

        jlblTempoDecorridoHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblTempoDecorridoHora.setForeground(new java.awt.Color(0, 0, 125));
        jlblTempoDecorridoHora.setText("02:15:22");

        jlblHoraAtual.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblHoraAtual.setText("Hora Atual:");

        jlblHoraAtualHora.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlblHoraAtualHora.setForeground(new java.awt.Color(0, 0, 125));
        jlblHoraAtualHora.setText("10:19:13");

        jbtnAdd1.setText("Voltar");
        jbtnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdd1ActionPerformed(evt);
            }
        });

        jlblNomePalestra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblNomePalestra.setText("Nome da palestra");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Palestra:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Palestrante:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Instituição:");

        jlblInstituicao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblInstituicao.setText("Instituicao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblNomePalestrante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblNomePalestra, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblHoraInicioPrevistaHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblTempoDecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jftfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblHoraInicioPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblHoraInicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlblHoraTerminoHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlblHoraTerminoPrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlblHoraTerminoPrevistoHora, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(jlblHoraTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlblTempoDecorridoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82)
                                    .addComponent(jlblHoraAtualHora, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jbtnFinalizarPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jbtnIniciarPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jlblOuvintes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblInformeCodigoBarras)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlblHoraAtualHora, jlblHoraInicioHora, jlblHoraInicioPrevistaHora, jlblHoraTerminoHora, jlblHoraTerminoPrevistoHora, jlblTempoDecorridoHora});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlblHoraInicio, jlblHoraInicioPrevista, jlblTempoDecorrido});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNomePalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblNomePalestrante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblInstituicao))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIniciarPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnFinalizarPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOuvintes)
                    .addComponent(jlblInformeCodigoBarras))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHoraInicio)
                            .addComponent(jlblHoraTermino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHoraInicioHora)
                            .addComponent(jlblHoraTerminoHora))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHoraInicioPrevista)
                            .addComponent(jlblHoraTerminoPrevista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHoraTerminoPrevistoHora)
                            .addComponent(jlblHoraInicioPrevistaHora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTempoDecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTempoDecorridoHora)
                            .addComponent(jlblHoraAtualHora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlblHoraAtualHora, jlblHoraInicioHora, jlblHoraInicioPrevistaHora, jlblHoraTerminoHora, jlblHoraTerminoPrevistoHora, jlblTempoDecorridoHora});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlblHoraAtual, jlblHoraInicio, jlblHoraInicioPrevista, jlblHoraTermino, jlblHoraTerminoPrevista, jlblTempoDecorrido});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jlblInstituicao, jlblNomePalestra, jlblNomePalestrante});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarPalestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarPalestraActionPerformed


  }//GEN-LAST:event_jbtnIniciarPalestraActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
       
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPalestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewPalestra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnAdd1;
    private javax.swing.JButton jbtnFinalizarPalestra;
    private javax.swing.JButton jbtnIniciarPalestra;
    private javax.swing.JFormattedTextField jftfCodigoBarras;
    private javax.swing.JLabel jlblHoraAtual;
    private javax.swing.JLabel jlblHoraAtualHora;
    private javax.swing.JLabel jlblHoraInicio;
    private javax.swing.JLabel jlblHoraInicioHora;
    private javax.swing.JLabel jlblHoraInicioPrevista;
    private javax.swing.JLabel jlblHoraInicioPrevistaHora;
    private javax.swing.JLabel jlblHoraTermino;
    private javax.swing.JLabel jlblHoraTerminoHora;
    private javax.swing.JLabel jlblHoraTerminoPrevista;
    private javax.swing.JLabel jlblHoraTerminoPrevistoHora;
    private javax.swing.JLabel jlblInformeCodigoBarras;
    private javax.swing.JLabel jlblInstituicao;
    private javax.swing.JLabel jlblNomePalestra;
    private javax.swing.JLabel jlblNomePalestrante;
    private javax.swing.JLabel jlblOuvintes;
    private javax.swing.JLabel jlblTempoDecorrido;
    private javax.swing.JLabel jlblTempoDecorridoHora;
    private java.util.List<model.Sessao> sessaoList;
    private javax.persistence.Query sessaoQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
