<div id="creditos">
    
    <h2>Créditos</h2>
    
    <h4>Organizadores</h4>
    
    <h4>Colaboradores</h4>
    
    <p>O sistema da Semana Acadêmica 2011 foi desenvolvido inteiramente em PHP utilizando o framework de desenvolvimento
    Zend, MySQL, jQuery e Ajax.</p>
    
    <h4>Modelagem</h4>
    <p>Jeferson Lemes (TA) <br />
    Thiago Krug (ES) <br />
    Lucas Capanelli (ES) <br />
    Thiago Lima (ES) <br />
    Maicon Venes (EE)<br /></p>
    
    <h4>Layout</h4>
    <p>Thiago Lima (ES)</p>
    
    <h4>Design de Logo</h4>
    <p>Lucas Arbiza (CC)</p>
    
    <h4>Banco de Dados</h4>
    <p>Thiago Krug (ES)</p>
    
    <h4>Codificação</h4>
    <p>Rafael Tavares (ES) <br />
    Thiago Lima (ES)</p>
    
</div>
