<h2>Usuarios Palestras</h2>
<br />
<script type="text/javascript">
    function imprimir(){
        td = document.getElementsByTagName("td");
        for (i=0; i < td.length; i++) {
            td[i].setAttribute("style", "border: black solid 1px");
        }
        table = document.getElementsByTagName("table");
        for (i=0; i < table.length; i++) {
            table[i].setAttribute("style", "border: black solid 1px");
        }
        var cods = $('#relatorio').html();
        w=window.open();
        w.document.write(cods);
        w.print();
        w.close();
    }
</script>

<div class="botao">
    <button onClick="imprimir()">Imprimir</button>
</div>

<!--<div id="relatorio">
    <ul>
<? // foreach ($this->usuarios as $usuario): ?>
            <li style="font-size: 12pt;font-weight: 100;">Nome:<? //= $this->FormatarNome($usuario->nome)    ?> - Instituição: <? //= $this->FormatarNome($usuario->instituicao)    ?> - Curso: <? //= $this->FormatarNome($usuario->curso)    ?>
<? // $sessoes = $usuario->findDependentRowset('Application_Model_DbTable_Sessao') ?>
                <ul>
<? // foreach ($sessoes as $sessao): ?>
                        <li style="font-size: 10pt;font-style: italic;"><? //= $sessao->findDependentRowset('Application_Model_DbTable_Palestra')->current()->nome_palestra    ?> - Data Entrada: <? //= $this->formatarDataHora($sessao->hora_entrada)    ?> - Data Saída: <? //= $this->formatarDataHora($sessao->hora_saida)    ?> - Tempo de permanência: <? //= $this->CalcularTempo($sessao->hora_entrada, $sessao->hora_saida)    ?></li>
<? // endforeach; ?>
                </ul>
            </li>
<? // endforeach; ?>
    </ul>
</div>-->

<div id="relatorio">

    <? foreach ($this->usuarios as $usuario): ?>
        <h2>Nome do Usuario: <?= $this->FormatarNome($usuario->nome) ?></h2>
        <h3>Instituição: <?= $this->FormatarNome($usuario->instituicao) ?></h3>
        <h3>Curso: <?= $this->FormatarNome($usuario->curso) ?></h3>
        <table class="tabela" name="<?= $this->FormatarNome($usuario->nome) ?>">
            <thead>
                <tr>
                    <td width="">Nome da Palestra</td>
                    <td width="">Nome do Palestrante</td>
                    <td width="">Instituição do Palestrante</td>
                    <td width="">Sala</td>
                    <td width="">Início Previsto</td>
                    <td width="">Fim Previsto</td>
                    <td width="">Início Real</td>
                    <td width="">Fim Real</td>
                    <td width="">Entrada do Usuario</td>
                    <td width="">Saída do Usuario</td>
                    <td width="">Tempo de Permanência</td>
                </tr>
            </thead>
            <? $sessoes = $usuario->findDependentRowset('Application_Model_DbTable_Sessao') ?>
            <? foreach ($sessoes as $sessao): ?>
                <? $palestra = $sessao->findDependentRowset('Application_Model_DbTable_Palestra')->current(); ?>
                <tbody>
                    <tr>
                        <td><?= $palestra->nome_palestra ?></td>
                        <td><?= $palestra->nome_palestrante ?></td>
                        <td><?= $palestra->instituicao ?></td>
                        <td><?= $palestra->sala ?></td>
                        <td><?= $this->formatarDataHora($palestra->hora_inicio_prevista) ?></td>
                        <td><?= $this->formatarDataHora($palestra->hora_fim_prevista) ?></td>
                        <td><?= $this->formatarDataHora($palestra->hora_inicio) ?></td>
                        <td><?= $this->formatarDataHora($palestra->hora_fim) ?></td>
                        <td><?= $this->formatarDataHora($sessao->hora_entrada) ?></td>
                        <td><?= $this->formatarDataHora($sessao->hora_saida) ?></td>
                        <td><?= $this->CalcularTempo($sessao->hora_entrada, $sessao->hora_saida) ?></td>
                    </tr>
                </tbody>
            <? endforeach; ?>
        </table>
        <br /><br /><hr style="border: black groove 3px;" /><br /><br />
    <? endforeach; ?>
</div>