<div style="margin:20px;">
    <div class="botao" style="font-size: 10px;">
        <a href="<?=$this->baseUrl('/admin/relatorio-codigo-barras-nao-impresso')?>">Codigos de Barras Não Impressos</a> 
        <a href="<?=$this->baseUrl('/admin/relatorio-codigo-barras-impresso')?>">Codigos de Barras Impressos</a>
        <a href="<?=$this->baseUrl('/admin/relatorio-ouvintes-palestras')?>">Relatório Ouvintes Palestras</a>
        <a href="<?=$this->baseUrl('/admin/relatorio-palestras-ouvintes')?>">Relatório Palestras Ouvintes</a>
    </div> 
</div>