<div style="margin:20px;">
    <div class="botao" style="font-size: 10px;">
        <a href="<?=$this->baseUrl('/admin/relatorio-codigo-barras-nao-impresso')?>">Codigos de Barras Não Impressos</a> 
        <a href="<?=$this->baseUrl('/admin/relatorio-codigo-barras-impresso')?>">Codigos de Barras Impressos</a>
        <a href="<?=$this->baseUrl('/admin/relatorio-usuarios-palestras')?>">Relatório Usuarios Palestras</a>
        <a href="<?=$this->baseUrl('/admin/relatorio-palestras-usuarios')?>">Relatório Palestras Usuarios</a>
    </div> 
</div>