<div class="box-topo">
    <h2>Usuarios Cadastrados no Sistema</h2>
    <ul class="tabela_controles">
<!--        <li><a href="<?//=$this->baseUrl('admin/pesquisar-usuario')?>" rel="tooltip" title="Pesquisar Usuario">
                <img height="24" width="24" alt="Pesquisar Usuario" src="<?//=$this->baseUrl('img/pesquisar.png')?>" border="0" /></a></li>-->
                
        <li><a href="<?=$this->baseUrl('admin/usuarios/filtro/isento')?>" rel="tooltip" title="Listar Usuarios Isentos">
                <img height="24" width="24" alt="Listar Usuarios Isentos" src="<?=$this->baseUrl('img/isento.png')?>" border="0" /></a></li>
                
        <li><a href="<?=$this->baseUrl('admin/usuarios/filtro/pago')?>" rel="tooltip" title="Listar Usuarios Pagos">
                <img height="24" width="24" alt="Listar Usuarios Pagos" src="<?=$this->baseUrl('img/pago.png')?>" border="0" /></a></li>
        
        <li><a href="<?=$this->baseUrl('admin/usuarios/filtro/naopago')?>" rel="tooltip" title="Listar Usuarios Não-Pagos">
                <img height="24" width="24" alt="Listar Usuarios Não-Pagos" src="<?=$this->baseUrl('img/naopago.png')?>" border="0" /></a></li>        
        
    </ul>
</div>
<?=$this->form?>
<div class="tabela">
    <table class="tabela" name="palestras">
        <thead>
            <tr>
                <td width="8%">ID</td>
                <td width="17%">Instituição</td>
                <td width="27%">Nome</td>
                <td width="10%">Cód. Barras</td>
                <td width="15%">Email Confirmado</td>
                <td width="15%">Pagamento</td>
                <td width="13%">Opções</td>
            </tr>
        </thead>
        
        <tbody>
            
            <?foreach($this->usuarios as $usuario):?>
            <tr>
                <td><?=$usuario->id_usuario?></td>
                <td><?=$usuario->instituicao?></td>
                <td><?=$usuario->nome?></td>
                <td><?=$usuario->codigo_barras?></td>
                <td><?=$usuario->email_confirmado ? 'Sim' : 'Não'?></td>
                <td><?=$this->FormatarPagamento($usuario->pagamento)?></td>
                <td>
                    <a href="<?=$this->baseUrl('/admin/ver-dados-usuario/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Ver dados do usuario"><img alt="Ver Dados do Usuario" width="16" height="16" src="<?=$this->baseUrl('img/editar.ico')?>" /></a>
                    <!--<a onClick="return confirm('Deseja deletar esse usuario?');" href="<?=$this->baseUrl('admin/deletar-usuario/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Deletar Usuario"><img alt="Deletar Usuario" width="16" height="16" src="<?=$this->baseUrl('img/apagar.png')?>" /></a> -->
                    <a onClick="return confirm('Deseja editar os dados desse usuario?');" href="<?=$this->baseUrl('admin/editar-usuario/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Editar dados do usuario"><img alt="Editar Usuario" width="16" height="16" src="<?=$this->baseUrl('img/editar.png')?>" /></a>
                    <a href="<?=$this->baseUrl('credenciamento/credenciar/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Credenciar usuário (Pagar e Imprimir)"><img width="16" height="16" src="<?=$this->baseUrl('img/marcarpago.ico')?>" /></a>
                    <a onClick="return confirm('Deseja marcar este usuario como Não-Pago?');" href="<?=$this->baseUrl('admin/alterar-pagamento/pagamento/naopago/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Marcar Usuario como não pago"><img alt="Marcar Usuario como não pago" width="16" height="16" src="<?=$this->baseUrl('img/marcarnaopago.ico')?>" /></a>
                    <!--<a onClick="return confirm('Deseja marcar este usuario como Pago?');" href="<?=$this->baseUrl('admin/alterar-pagamento/pagamento/pago/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Marcar Usuario como Pago"><img alt="Marcar Usuario como pago" width="16" height="16" src="<?=$this->baseUrl('img/marcarpago.ico')?>" /></a>
                    <a onClick="return confirm('Deseja marcar este usuario como Isento?');" href="<?=$this->baseUrl('admin/alterar-pagamento/pagamento/isento/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Marcar Usuario como Isento"><img alt="Marcar Usuario como isento" width="16" height="16" src="<?=$this->baseUrl('img/marcarisento.ico')?>" /></a> -->
                </td>
            </tr>
            <?endforeach;?>
            
        </tbody>
        
    </table>
</div>
<div class="box-footer">
    <span class="txt_pequeno txt_light">Existem <?=count($this->usuarios)?> usuarios cadastrados no sistema.</span>
    <br />
    <?if(empty($this->filtro) == false):?>
        <span class="txt_pequeno txt_light" style="font-weight: bold;"><?=empty($this->filtro) ? '':'Filtrado por '.$this->filtro?></span>
        <span class="txt_pequeno txt_light" style="font-weight: bold;"><a href="<?=$this->baseUrl('/admin/usuarios')?>">Remover Filtro</a></span>
    <?endif;?>
</div>