<div class="box-topo">
    <h2>Usuários Cadastrados</h2>
    <ul class="tabela_controles">
        <li><a href="<?=$this->baseUrl('admin/inserir-editar-usuario')?>" rel="tooltip" title="Cadastrar Usuário">
                <img height="24" width="24" alt="Insere Novo Usuário" src="<?=$this->baseUrl('img/historico.png')?>" border="0" /></a></li>
    </ul>
</div>
<div class="tabela">
    <table class="tabela" name="usuarios">
        <thead>
            <tr>
                <td width="30%">Nome</td>
                <td width="15%">Login</td>
                <td width="25">E-mail</td>
                <td width="20%">Tipo</td>
                <td width="10%">Opções</td>
            </tr>
        </thead>
        <tbody>
            <?foreach($this->usuarios as $usuario):?>
            <tr>
                <td><?=$usuario->nome?></td>
                <td><?=$usuario->email?></td>
                <td><?=$usuario->email?></td>
                <td><?=$usuario->findDependentRowset('Application_Model_DbTable_TipoUsuario')->current()->nome?></td>
                <td>
                    <a href="<?=$this->baseUrl('/admin/inserir-editar-usuario/id_usuario/'.$usuario->id_usuario)?>" rel="tooltip" title="Editar dados do usuário"><img src="<?=$this->baseUrl('/img/editar.png')?>" width="16" height="16" border="0" alt="" /></a>
                    
                    <a href="<?=$this->baseUrl('/admin/apagar-usuario/id_usuario/'.$usuario->id_usuario)?>" onClick="return confirm('Deseja apagar o usuário do Sistema?');" rel="tooltip" title="Apagar Usuário do sistema"><img src="<?=$this->baseUrl('/img/apagar.png')?>" width="16" height="16" border="0" alt="" /></a>
                </td>
            </tr>
            <?endforeach;?>
        </tbody>
    </table>
</div>
<div class="box-footer">
    <span class="txt_pequeno txt_light">Existem <?=count($this->usuarios)?> usuários cadastrados no sistema.</span>
</div>